# Generated by Django 4.2.15 on 2025-01-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0003_profile_remove_seller_user_delete_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
