# Generated by Django 4.2.15 on 2025-01-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.JSONField(default=list, verbose_name='Cart Item IDs'),
        ),
    ]
