# Generated by Django 4.2.15 on 2025-01-21 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0002_remove_order_cart_item_order_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_api.shippingaddress'),
        ),
    ]
