# Generated by Django 4.2.15 on 2025-01-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profile_id',
            new_name='user_id',
        ),
    ]
