# Generated by Django 4.2.15 on 2025-01-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0004_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
